#!/usr/bin/env bash

###############################################################################
# LABCTL Configuration
###############################################################################

#
# Application
#
readonly NAME="LABCTL"
readonly VERSION="1.0.0"
: "${LABCTL_HOME:?LABCTL_HOME is not set}"
# Directories
#
readonly LOG_DIR="$LABCTL_HOME/.local/share/labctl/logs"

#
# Log file
#
readonly LOG_FILE="$LOG_DIR/labctl.log"

#
# NetworkManager Profile Names
#
readonly PROFILE_NAT="NAT"
readonly PROFILE_LAB="LAB"
readonly PROFILE_BRIDGED="BRIDGED"
readonly PROFILE_NATNET="NATNET"

#
# Default Mode
#
readonly DEFAULT_PROFILE="$PROFILE_NAT"

#
# Logging
#
readonly LOG_DATE_FORMAT="+%Y-%m-%d %H:%M:%S"

#
# Miscellaneous
#
readonly TRUE=0
readonly FALSE=1

# Debugging
readonly DEBUG=false


#######################################
# Internal Directories
#######################################

readonly LIB_DIR="${LABCTL_HOME}/lib"
readonly COMMAND_DIR="${LABCTL_HOME}/commands"
readonly TEST_DIR="${LABCTL_HOME}/tests"

#######################################
# Supported Profiles
#######################################

readonly SUPPORTED_PROFILES=(
    update
    contain
    lab
    bridged
)


#######################################
# Required System Commands
#######################################

readonly REQUIRED_COMMANDS=(
    nmcli
    ip
    awk
    grep
    sed
)

#######################################
# Exit Codes
#######################################

readonly EXIT_SUCCESS=0
readonly EXIT_FAILURE=1
readonly EXIT_INVALID_ARGUMENT=2
readonly EXIT_PERMISSION_DENIED=3
readonly EXIT_CONFIGURATION_ERROR=4
readonly EXIT_NETWORK_ERROR=5
readonly EXIT_DEPENDENCY_MISSING=6
readonly EXIT_UNKNOWN_ERROR=99

###############################################################################
# Network Verification
###############################################################################

PING_TIMEOUT=2
DNS_TARGET="1.1.1.1"
INTERNET_TARGET="8.8.8.8"
