#!/usr/bin/env bash

###############################################################################
# LABCTL Configuration
###############################################################################

#
# Application
#
readonly NAME="LABCTL"
readonly VERSION="1.0.0"
# readonly LABCTL_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
#
# Directories
#
readonly LOG_DIR="$HOME/.local/share/labctl/logs"

#
# Log file
#
readonly LOG_FILE="$LOG_DIR/labctl.log"

#
# NetworkManager Profile Names
#
readonly PROFILE_NAT="NAT"
readonly PROFILE_LAB="LAB"
readonly PROFILE_BRIDGED="BRIDGED"
readonly PROFILE_NATNET="NATNET"

#
# Default Mode
#
readonly DEFAULT_PROFILE="$PROFILE_NAT"

#
# Logging
#
readonly LOG_DATE_FORMAT="+%Y-%m-%d %H:%M:%S"

#
# Miscellaneous
#
readonly TRUE=0
readonly FALSE=1

# Debugging
readonly DEBUG=false
